#!/usr/bin/env bash
set -e

TAG=0.2.0.0

# exit if there is evidence of installation
[ -e ./purp.tar.gz ] && exit 0;

# remove stubs
rm ./purp

# osx or linux install
if [ "$(uname -s)" == "Darwin" ]
then
  curl --location --output ./purp.tar.gz --silent https://github.com/justinwoo/purp/releases/download/$TAG/macos.tar.gz
else
  wget -O ./purp.tar.gz https://github.com/justinwoo/purp/releases/download/$TAG/linux.tar.gz
fi

# unpack
tar -xvf ./purp.tar.gz -C ./
